# Default values for app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


db:
  ReleaseName: statefulset-db
  namespace: default
  container:
    name: db
    image: saltedcucumber/react-java-application-main-db
  labels:
    app: db
  serviceName: db
  port: 3306
  volumes:
    volumeMounts:
      path: /var/lib/mysql
      name: persisent-volume-db
    persistentVolumeClaim:
      claimName: persisent-volume-claim-db
      storageClassName: manual
    hostPath: "/home/test/PV"
    capacity: 5Gi
    labels: local
  Service:
    name: service-db
    port: 3306
  
frontend:
  ReleaseName: deployment-frontend
  namespace: default
  container:
    name: frontend
    image: saltedcucumber/react-java-application-main-frontend:2
    port: 3000
  labels: frontend 
  Service:
    name: service-frontend
  Ingress:
    name: ingress-app
    ingressClassName: nginx
    host: host1
    pathType: Prefix
    service: service-frontend
    port: 3000
     
  
backend:
    ReleaseName: deployment-backend
    service:
      name: service-backend
      namespace: default
    labels:
      app: backend
    container:
      name: backend 
      image: saltedcucumber/react-java-application-main-backend
      port: 8080
    env:
      SpringDatasourceUrl:
        name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://service-db:3306/fullstack
      SpringDatasourceUsername:  
        name: SPRING_DATASOURCE_USERNAME
        value: root
      SpringDatasourcePassword:  
        name: SPRING_DATASOURCE_PASSWORD
        value: root  
    Service:
      name: service-backend
      namespace: default
      port: 8080
