apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.Ingress.name }}
  annotations:
spec:
  ingressClassName: {{ .Values.frontend.Ingress.ingressClassName }}
  rules:
  - host: {{ .Values.frontend.Ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.frontend.Ingress.pathType }}
        path: "/"
        backend:
          service:
            name: {{ .Values.frontend.Ingress.service }}
            port:
              number: {{ .Values.frontend.Ingress.port }}
