---
# tasks file for iptable
- name: Allow HTTP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Allow HTTP

- name: Forward port 80 to 8600
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: enp0s3
    protocol: tcp
    match: tcp
    destination_port: 8600
    jump: REDIRECT
    to_ports: 80
    comment: Redirect web traffic to port 8600