- hosts:
    - all
  tasks:

    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes
     
    - name: Check If docker-compose Is Installed
      command: docker-compose --version
      register: docker_compose_valid
      ignore_errors: yes 

    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes
      tags:
        - dependencies

    - name: GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - gpt-key

    - name: repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      tags:
        - docker_repository
        
    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      when: docker_valid.failed
      tags:
        - install_docker
        
    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
      when: docker_compose_valid.failed
      tags:
        - install_docker-compose

    - name: create docker user 
      ansible.builtin.user:
        name: docker
        groups: docker
        state: present
        shell: /bin/bash
        system: false
        create_home: true
        home: /home/docker
      tags:
        - docker_user
    
   
    

