---
# tasks file for ConfigereNginx
- name: copy passwd file to server 
  copy:
        src: /etc/apache2
        dest: /etc 
        owner: root
        group: root        
        mode: 0644
        
- name: Configure Nginx
  template:
      src: templates/default
      dest: /etc/nginx/sites-available/default

- name: restart nginx
  service:
        name: nginx
        state: restarted