apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.volumes.volumeMounts.name }}
  labels:
    type: {{ .Values.db.volumes.labels }}
spec:
  claimRef:
    namespace: {{ .Values.db.namespace }}
    name: {{ .Values.db.volumes.persistentVolumeClaim.claimName }}
  storageClassName: {{ .Values.db.volumes.persistentVolumeClaim.storageClassName }}
  capacity:
    storage: {{ .Values.db.volumes.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.volumes.hostPath }}

