apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.Service.name }}
  namespace: {{ .Values.db.namespace }}
spec:
  selector:
    app: {{ .Values.db.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.Service.port }}
      targetPort: {{ .Values.db.Service.port }}