apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.Service.name }}
  namespace: {{ .Values.backend.Service.namespace }}
spec:
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.Service.port }}
      targetPort: {{ .Values.backend.Service.port }}