---
# tasks file for DockerInstall
- name: GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: repository docker
  apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

        
- name: install docker
  apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

- name: Install docker-compose
  get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

- name: create docker user 
  ansible.builtin.user:
        name: docker
        groups: docker
        state: present
        shell: /bin/bash
        system: false
        create_home: true
        home: /home/docker
